title: Learning Theory
description: Learning Theory Course, FUM, CS Dept.
theme: just-the-docs
author: M. Amintoosi

url: https://fum-cs.github.io/learning-theory

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/fum-cs-logo.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/fum-logo.ico"

aux_links:
  CS Dept.:
    - 'https://fumcs.github.io'
  Mahmood Amintoosi:
    - 'https://mamintoosi.github.io'
  Class Repository:
    - 'https://github.com/fum-cs/learning-theory'

mathjax:
  source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
  config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: true
  profile: false

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Ferdowsi University of Mashhad <a href=\"https://fumcs.github.io/\">Computer Science Dept.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
# gh_edit_link: true # show or hide edit this page link
# gh_edit_link_text: "Edit this page on GitHub."
# gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # the github URL for your repo
# gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
# gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
